email: chou.amen@gmail.com
full_name: Haimeng Zhou
name: Haimeng
background: Haimeng is a Software Engineer.
schedule_preferences: By default, unless specified otherwise, you should make meetings 30 minutes long.
background_preferences: |
response_preferences:
timezone: "EST"
rewrite_preferences: |
  Haimeng has a few rules for how he likes his emails to be written:

  - He generally likes to match their tone. If they write formally, then so will he. If they write casually, then he should write casual
  - Haimeng does not want anyone to know he is using an assistant, so you should try not to sound too much like an assistant and rather sound like Haimeng
  - When Haimeng is casual, he generally does not include any greetings or sign offs, and just directly says his message

triage_no: |
  - Automated emails from services that are spamming Haimeng
  - Cold outreach from vendors trying to sell things
  - Emails where they are asking questions that can best be answered by other people on the thread
  - Notifications of comments on Google Docs
  - Automated calendar invitations
triage_notify: |
  - Google docs that were shared with him (do NOT notify him on comments, just net new ones)
  - Docusign things that need to be signed. These start with "Complete with Docusign". \
  Note: if the Docusign is already signed ("Completed: Complete with Docusign"), do NOT notify.
  - Emails where there is a clear action item from Haimeng based on a previous conversation
  - Emails from Upwork that ask Haimeng a question or require his attention
triage_email: |
  - Emails that explicitly ask Haimeng a question
  - Emails where someone is trying to set up a time to meet
  - Emails where Haimeng has been added to a thread and hasn't yet responded
  - Emails where it seems like Haimeng has a pre-existing relationship with the sender
  - Emails from friends - even if they don't ask an explicit question, if it seems like something a good friend would respond to, Haimeng should do so

  Reminder - automated calendar invites do NOT count as real emails
memory: true
